# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u6tA8jN89c-7fw6s-fU1zSxI1jxvYtXR
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import bernoulli
from scipy.stats import norm
from scipy.stats import binom

#number of simulations
simulations=1000

#number of questions is each simulation
n =  20

#Probability of  solving a question
p = 1/2

#Simulating Event 
data_binom = binom.rvs(n,p,size=simulations)

fullfilling_simulations=0
for i in range(1000):
    if data_binom[i]>=12:
        fullfilling_simulations +=1

print("Probability of getting 12 or more answers correct by simulations:",fullfilling_simulations/simulations)
print("Probability of getting 12 or more answers correct by theoritical calculations:",0.25172233581)